### PR TITLE
removed extra 'irure' and changed 'k' to 'c' in 'cupiditat'

### PR DESCRIPTION
**Pull request by 23jan175**
Changed typos from the Latin I know.

### CODE REVIEW

**Comment by sgeinitz** [comment]
Hi, not sure who this is. Either leave your name here, or put your gh username (23jan175) in Canvas under this assignment.

**Comment by 23jan175** [comment]
Sorry,
This is Emily Carrillo-Ramirez.
Thank you

**Comment by sgeinitz** [comment]
Thanks, Emily, in hindsight that should have been part of the directions.

**Comment by 23jan175** [comment]
Sorry it was a pretty random username. I can change it to something that is
similar to my name. No worries.

**Pull request merged**
